# Generated by Django 4.2.1 on 2023-05-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'verbose_name_plural': 'income'},
        ),
    ]
