# Generated by Django 4.2.1 on 2023-05-18 00:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userincome', '0002_alter_userincome_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIncome',
            new_name='Income',
        ),
        migrations.AlterModelOptions(
            name='income',
            options={},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'source'},
        ),
    ]
