# Generated by Django 4.2.1 on 2023-05-18 00:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userincome', '0003_rename_userincome_income_alter_income_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Income',
            new_name='UserIncome',
        ),
        migrations.AlterModelOptions(
            name='userincome',
            options={'verbose_name_plural': 'income'},
        ),
    ]
