# Generated by Django 4.2.1 on 2023-05-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0005_alter_source_options_alter_userincome_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincome',
            old_name='src',
            new_name='source',
        ),
    ]
