# Generated by Django 4.2.1 on 2023-05-18 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0006_rename_src_userincome_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'source'},
        ),
    ]
