# Generated by Django 4.2.1 on 2023-05-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0007_alter_source_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
    ]
